//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winpenguins.rc
//
#define IDAPPLY                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WINpenguins_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_ICON                        128
#define IDB_EXPLOSION                   131
#define IDR_WALKER                      138
#define IDR_RWALKER                     139
#define IDR_BOMBER                      142
#define IDR_CLIMBER                     143
#define IDR_RCLIMBER                    144
#define IDR_FALLER                      145
#define IDR_FLOATER                     147
#define IDR_TUMBLER                     148
#define IDD_TOON                        149
#define IDR_SYSTRAY                     151
#define IDB_WALKER                      153
#define IDB_CLIMBER                     154
#define IDB_FALLER                      155
#define IDB_FLOATER                     156
#define IDB_TUMBLER                     157
#define IDB_BOMBER                      158
#define IDB_BOMBERMSK                   159
#define IDB_CLIMBERMSK                  161
#define IDB_EXPLOSIONMSK                162
#define IDB_FALLERMSK                   163
#define IDB_FLOATERMSK                  164
#define IDB_TUMBLERMSK                  165
#define IDB_WALKERMSK                   166
#define IDB_SANTA_WALKERMSK             172
#define IDB_SANTA_CLIMBERMSK            173
#define IDB_SANTA_WALKER                174
#define IDB_SANTA_CLIMBER               175
#define IDR_SOUND_BOOM                  176
#define IDR_SOUND_POP                   177
#define IDR_SOUND_SPLAT                 178
#define IDB_READER                      180
#define IDB_READERMSK                   181
#define IDB_BALLOONER                   182
#define IDB_BALLOONERMSK                183
#define IDB_SKATEBOARDER                184
#define IDB_SKATEBOARDERMSK             185
#define IDB_SKATEBOARDER_CLIMBER        186
#define IDB_SKATEBOARDER_CLIMBERMSK     187
#define IDB_SPLAT                       188
#define IDB_SPLATMSK                    189
#define IDB_EXIT                        190
#define IDB_EXITMSK                     191
#define IDB_SUPER                       192
#define IDB_SUPERMSK                    193
#define IDB_WALKERLARGE                 194
#define IDB_WALKERLARGEMSK              195
#define IDB_CLIMBERLARGE                196
#define IDB_CLIMBERLARGEMSK             197
#define IDB_FALLERLARGE                 198
#define IDB_FALLERLARGEMSK              199
#define IDB_FLOATERLARGE                200
#define IDB_FLOATERLARGEMSK             201
#define IDB_TUMBLERLARGE                202
#define IDB_TUMBLERLARGEMSK             203
#define IDB_BOMBERLARGE                 204
#define IDB_BOMBERLARGEMSK              205
#define IDB_EXPLOSIONLARGE              206
#define IDB_EXPLOSIONLARGEMSK           207
#define IDB_SANTA_WALKERLARGE           208
#define IDB_SANTA_WALKERLARGEMSK        209
#define IDB_SANTA_CLIMBERLARGE          210
#define IDB_SANTA_CLIMBERLARGEMSK       211
#define IDB_READERLARGE                 212
#define IDB_READERLARGEMSK              213
#define IDB_BALLOONERLARGE              214
#define IDB_BALLOONERLARGEMSK           215
#define IDB_SKATEBOARDERLARGE           216
#define IDB_SKATEBOARDERLARGEMSK        217
#define IDB_SKATEBOARDER_CLIMBERLARGE   218
#define IDB_SKATEBOARDER_CLIMBERLARGEMSK 219
#define IDB_SPLATLARGE                  220
#define IDB_SPLATLARGEMSK               221
#define IDB_EXITLARGE                   222
#define IDB_EXITLARGEMSK                223
#define IDB_SUPERLARGE                  224
#define IDB_SUPERLARGEMSK               225
#define IDB_SKATEBOARDER_CLIMBER_DOWN   226
#define IDB_SKATEBOARDER_CLIMBER_DOWNMSK 227
#define IDB_SKATEBOARDER_CLIMBER_DOWNLARGE 228
#define IDB_SKATEBOARDER_CLIMBER_DOWNLARGEMSK 229
#define IDB_CLIMBER_DOWN                230
#define IDB_CLIMBER_DOWNMSK             231
#define IDB_CLIMBER_DOWNLARGE           232
#define IDB_CLIMBER_DOWNLARGEMSK        233
#define IDB_WALKER_UPSIDE_DOWN          234
#define IDB_WALKER_UPSIDE_DOWNMSK       235
#define IDB_WALKER_UPSIDE_DOWNLARGE     236
#define IDB_WALKER_UPSIDE_DOWNLARGEMSK  237
#define IDB_SKATEBOARDER_UPSIDE_DOWN    238
#define IDB_SKATEBOARDER_UPSIDE_DOWNMSK 239
#define IDB_SKATEBOARDER_UPSIDE_DOWNLARGE 240
#define IDB_SKATEBOARDER_UPSIDE_DOWNLARGEMSK 241
#define IDB_SANTA_WALKER_UPSIDE_DOWN    242
#define IDB_SANTA_WALKER_UPSIDE_DOWNMSK 243
#define IDB_SANTA_CLIMBER_DOWN          244
#define IDB_SANTA_CLIMBER_DOWNMSK       245
#define IDB_SANTA_WALKER_UPSIDE_DOWNLARGE 246
#define IDB_SANTA_WALKER_UPSIDE_DOWNLARGEMSK 247
#define IDB_SANTA_CLIMBER_DOWNLARGE     248
#define IDB_SANTA_CLIMBER_DOWNLARGEMSK  249
#define IDC_SLIDER1                     1000
#define IDC_PENGUINCOUNT                1000
#define IDC_SLIDER3                     1002
#define IDC_ANIWALKER                   1003
#define IDC_SLIDER4                     1003
#define IDC_SPEED                       1003
#define IDC_SPLAT                       1004
#define IDC_ALPHA                       1005
#define IDC_SANTA                       1006
#define IDC_PENGUINSIZE                 1007
#define IDC_SOUNDENABLED                1011
#define IDC_STATIC_URL                  1012
#define ID_EXIT                         32772
#define ID_OPTIONS                      32774
#define ID_ABOUT                        32775
#define ID_SCREENCAP                    32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
